apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "mta-service-backstage"
  annotations:
    - backstage.io/managed-by-location: https://github.com/rgolangh/mta-service-backstage/edit/master/catalog-info.yaml
    - janus-idp.io/workflows/id: bar
    - janus-idp.io/tekton-enabled : 'true'
    - janus-idp.io/workflows-enabled : 'true'
    
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  providesApis:
    - mta-application-analysis

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Migrate Workloads to Kubernetes (move2kube)"
  annotations:
    - backstage.io/managed-by-location: https://github.com/rgolangh/mta-service-backstage/edit/master/catalog-info.yaml
    - janus-idp.io/workflows/id: bar
    - janus-idp.io/tekton-enabled : 'true'
    - janus-idp.io/workflows-enabled : 'true'
    
spec:
  type: workflow
  owner: user:guest
  lifecycle: experimental
  providesApis:
    - move2kube

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: move2kube
  description: Perform an MTA analisys for an application
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  system: something
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Move 2 Kube
      license:
        name: MIT
    servers:
      - url: http://example.org/v1/move2kube
    paths:
      /:
        post:
          summary: invoke the workflow
