apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "mta-service-backstage"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  providesApis:
    - application-analysis
